nyc_lakehouse:
  target: dev
  outputs:
    dev:
      type: spark
      method: session
      schema: silver
      host: localhost
      threads: 1
    bq:
      type: bigquery
      method: oauth
      project: nyc-lakehouse
      dataset: lakehouse
      location: US
      threads: 4