version: 2

models:
  - name: stg_yellow
    columns:
      - name: pickup_at
        tests:
          - not_null
  - name: gold_weather_impact
    columns:
      - name: weather_condition
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['clear', 'rain', 'snow']
  - name: gold_borough_demand
    columns:
      - name: pickup_borough
        tests:
          - not_null